apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: secretKey
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
    - secretKey: postgresqlPassword
      remoteRef:
        key: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: redisPassword
      remoteRef:
        key: AUTHENTIK_REDIS__PASSWORD