apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secrets
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secrets
  data:
    - secretKey: tunnelToken
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN