apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kimai-secrets
  namespace: kimai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: kimai-secrets
  data:
    - secretKey: adminPassword
      remoteRef:
        key: KIMAI_ADMIN_PASSWORD
    - secretKey: mariadbPassword
      remoteRef:
        key: KIMAI_MARIADB_PASSWORD
    - secretKey: mariadbRootPassword
      remoteRef:
        key: KIMAI_MARIADB_ROOT_PASSWORD