apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kimai-secrets
  namespace: kimai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: kimai-secrets
  data:
    - secretKey: admin-password
      remoteRef:
        key: KIMAI_ADMIN_PASSWORD
    - secretKey: mariadb-password
      remoteRef:
        key: KIMAI_MARIADB_PASSWORD
    - secretKey: mariadb-root-password
      remoteRef:
        key: KIMAI_MARIADB_ROOT_PASSWORD
    - secretKey: app-secret
      remoteRef:
        key: KIMAI_APP_SECRET
    - secretKey: mailer-url
      remoteRef:
        key: KIMAI_MAILER_URL
    - secretKey: database-url
      remoteRef:
        key: KIMAI_DATABASE_URL
    - secretKey: kimai-cert
      remoteRef:
        key: KIMAI_CERT