apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mattermost-secrets
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: mattermost-secrets
  data:
    - secretKey: mysql-password
      remoteRef:
        key: MATTERMOST_MYSQL_PASSWORD
    - secretKey: mysql-root-password
      remoteRef:
        key: MATTERMOST_MYSQL_ROOT_PASSWORD
    - secretKey: mysql-dsn
      remoteRef:
        key: MATTERMOST_DSN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mattermost-dbsecret
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: mattermost-mattermost-team-edition-mattermost-dbsecret
  data:
    - secretKey: mattermost.dbsecret
      remoteRef:
        key: MATTERMOST_DB_SECRET