apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://agones.dev/chart/stable
    chart: agones
    targetRevision: 1.44.0
    helm:
      values: |
        agones:
          featureGates: "SidecarContainers=false"
        gameservers:
          namespaces:
            - default
  destination:
    server: https://kubernetes.default.svc
    namespace: agones-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true