apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jitsi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jitsi-contrib.github.io/jitsi-helm/
    chart: jitsi-meet
    targetRevision: "1.3.8"
    helm:
      valuesObject:
        publicURL: "https://meet.kleff.ca"
        jvb:
          publicIPs:
            - 23.233.180.65 
          service:
            type: NodePort
            udpPort: 10000
            tcpPort: 4443
        web:
          replicaCount: 1
        prosody:
          replicaCount: 1
        jicofo:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: jitsi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true