apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NathanRoos/ArgoCD
    path: yamls/kanboard
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kanboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true