---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanboard-config
  namespace: kanboard
data:
  config.php: |
    <?php
    define('APPLICATION_URL', 'https://kanboard.kleff.ca/');
    define('PLUGIN_INSTALLER', true);
