apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanboard-data
  namespace: kanboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  namespace: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      containers:
        - name: kanboard
          image: kanboard/kanboard:latest
          ports:
            - containerPort: 80
          env:
            - name: KANBOARD_REVERSE_PROXY_AUTH
              value: "true"
            - name: KANBOARD_REVERSE_PROXY_USER_HEADER
              value: "HTTP_X_AUTHENTIK_USERNAME"
            - name: TRUSTED_PROXY_NETWORKS
              value: "0.0.0.0/0"
            - name: KANBOARD_REVERSE_PROXY_AUTO_CREATE_USER
              value: "true"
            - name: KANBOARD_REVERSE_PROXY_DEFAULT_ADMIN_ROLE
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /var/www/app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kanboard-data
---
apiVersion: v1
kind: Service
metadata:
  name: kanboard
  namespace: kanboard
spec:
  selector:
    app: kanboard
  ports:
    - port: 80
      targetPort: 80