apiVersion: v1
kind: ConfigMap
metadata:
  name: kimai-saml-config
  namespace: kimai
data:
  local.yaml: |
    kimai:
      saml:
        activate: true
        title: "Login with SAML"
        roles:
          attribute: 'groups'
          mapping:
            - { saml: 'admins', kimai: 'ROLE_ADMIN' }
            - { saml: 'users', kimai: 'ROLE_USER' }
        connection:
          baseurl: "https://kimai.kleff.ca/auth/saml/"
        mapping:
          - { saml: 'email', kimai: 'email' }
          - { saml: 'username', kimai: 'username' }
          - { saml: 'username', kimai: 'alias' }