apiVersion: v1
kind: ConfigMap
metadata:
  name: kimai-saml-config
  namespace: kimai
data:
  local.yaml: |
    kimai:
      saml:
        activate: true
        title: "Login with SAML"
        connection:
          baseurl: "https://kimai.kleff.ca/auth/saml/"
          sp:
            entityId: "https://kimai.kleff.ca/auth/saml"
            assertionConsumerService:
              url: "https://kimai.kleff.ca/auth/saml/acs"
          idp:
            entityId: "https://auth.kleff.ca/"
            singleSignOnService:
              url: "https://auth.kleff.ca/application/saml/kimai/sso/binding/redirect/"
            x509cert: "MIIFUzCCAzugAwIBAgIRAJ0nBplugUromWulp3mRN+AwDQYJKoZIhvcNAQELBQAwHTEbMBkGA1UEAwwSYXV0aGVudGlrIDIwMjYuMi4xMB4XDTI2MDMwNzA0MDAyOVoXDTI3MDMwODA0MDAyOVowVjEqMCgGA1UEAwwhYXV0aGVudGlrIFNlbGYtc2lnbmVkIENlcnRpZmljYXRlMRIwEAYDVQQKDAlhdXRoZW50aWsxFDASBgNVBAsMC1NlbGYtc2lnbmVkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnB/i8QHSSE7uSpNHmUv1ANtN8GcLgMbo9aD0gY9CtUAuQNxmaUoL4z3L7kYXCheMJVaKns8XJ5LCd38mO4kJyCzpBac02Zxw0TwfmTg6Bj/4/tdA7GOFX+Nwi5K7tJs8o4MCCC2MDBsRRHAMDIqvF0DXjHJcs1jKzvaXWWBbFH53LmtqKQLfzHxWoTKJ2MfSw2c7kz5VJvzUVKVPnlwDxzFKBDibIj9jt69XHwX0QlzS+fR64//ZMgEJ7EKSuls0QjZ6FKP8AyST5nsdDkXpHAXh3jXrKcDKxLfLXx/CwOChoZObXilRThQJrCWlK0V1fcJLNeMseW/ykJ6tLUoLNxCFiOBN925y18lo/4u7sS4R4wkDWKdfITcB0waRh/cLA1D/OfPs7oUiJYhSuUYGnpwny8PDkQyl2eysb2ad9H2iYDdkBOoQyEJCHbzK+zTKLuMLNmxNNlSy6OsaKHJ5wshrvHZ/KbylCefsHo4x6O+izoCr54Cw0AjC+ykuDslcoPw5M+i2rBvP0xncaII5+rc0NxGLU92zauhw79HhD41XbaYa1bHmZfp2mrCpw1kZg3uTV777oqXV1Xj9kqeS5nzGxChzPLaWbcfdYNyjNu+YEK0f6LUB8dt6JDfExFYTf6olUBb0ZKIPurJCBdpHRab4foNHe2AxNUOIfnvXZvUCAwEAAaNVMFMwUQYDVR0RAQH/BEcwRYJDZ0kzblY4QllnYWxHSWVrdDJ0ZWdSN2VCMERtOERoNDRLYmg2UDhGMi5zZWxmLXNpZ25lZC5nb2F1dGhlbnRpay5pbzANBgkqhkiG9w0BAQsFAAOCAgEAeaJOwlkiB39soFTDP6Wtn+7O9BCT9fKdgABGXinfAjFSnMmr5J3LbSm+O9BnJec27eGXuxOUjD0Yg63QvoYYkw2bRr6Wmgkfp1eto8sXMEXEvRv2PundtVof8BdZnz+nYvY1v+2yeES2LXQjXXJfL9qaKuGeVbPWAL58jDxt4/DOgzVkxSNcL+fhyybybb+7EjPrEToZ2JDMJCUaXzXqkZ7HNarmm8cTmXlzv9p17kVCBHk3WfnRZxNjxUGryIAAJY5l8YTm9yPeJLAd/nhNSiNcsoGd73hsyQWQJ4A202V7sLrwmH4h8QD6/7X4QJGHr26easozLnbFP7rfiVP958uY4G9PyqjKsYAi+YBtAL/tw6NW2rMArlGOSsgKDDMfPkERoAPPqjyf2nXNHJMi/vq92WgIPCKIQnpm8sRhLB+I00M8WPSpM+OFgYlgvkgfOQ8BR/OdCqi3JML85iT8prrwUH+yvV1YOAT90X8dAiUJzYs/f07ImkkaD3OPQPVE00GZzgrzST+bCMw5pPbe+uSM6d48apxBybQFsoXbAxPcroj+oKxVPkF9fU1NPOa7RbnqZdudM6PO2osgTxTRPJcnBGs6GRryDA529ec+it2HYE8AkWjUid0pBJ8ruqUbLUFbj8VhC7pOzXLvwctgNeQ74Jqwy5/yj9IMARJ3Bd8="
        mapping:
          - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: 'email' }
          - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: 'username' }
          - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: 'alias' }