apiVersion: v1
kind: ConfigMap
metadata:
  name: kimai-saml-config
  namespace: kimai
data:
  local.yaml: |
    kimai:
      saml:
        connection:
          mapping:
            - { saml: 'email', kimai: 'email' }
            - { saml: 'username', kimai: 'username' }
            - { saml: 'username', kimai: 'alias' }
          defaults:
            role: ROLE_USER
            timezone: America/Toronto
            language: en